CREATE COLUMN TABLE "EXT"."CSE_DEBUG_HIST"(
	"TENANTID" VARCHAR(4),
	"DATETIME" LONGDATE CS_LONGDATE NOT NULL,
	"PROCESO" VARCHAR(400),
	"VALUE" INTEGER CS_INT,
	"TEXT" VARCHAR(4000)
)
UNLOAD PRIORITY 5 AUTO MERGE;