CREATE OR REPLACE FUNCTION EXT.GET_POLIZAS_CREDITO_ERROR_FICHERO(i_FILENAME VARCHAR(250)) 
/*
	----------------------------------------------------------------------------------------------- 
	| Author: Samuel Miralles Manresa 
	| Company: Inycom 
	| Initial Version Date: 27-11-2024
	| v02 Date: 11-12-2024
	|---------------------------------------------------------------------------------------------- 
	| fichero MVCAR
    | Muestra los registros que no coinciden en cartera
	| 
	| v01: versión inicial
	| v02: se añade el filtro para descartar los registros que el período de intermediación está fuera de la fecha de vigencia	
	| v03: SMM 20260324 Control si existe mediador o está dado de baja
	|
	----------------------------------------------------------------------------------------------- 
*/
	RETURNS TABLE (
		MOTIVO NVARCHAR(250)
		, IDMODALIDAD SMALLINT
		, NUM_POLIZA BIGINT
		, ANUALIDAD BIGINT
		, IDMEDIADOR NVARCHAR(20)
		, FECHA_EFECTO DATE
		, FECHA_VENCIMIENTO DATE
		, FECHA_INICIO DATE
		, FECHA_FIN DATE
		, BATCHNAME NVARCHAR(250)
	) LANGUAGE SQLSCRIPT 
	AS
	BEGIN
		RETURN SELECT DISTINCT
				CASE
					WHEN NOT EXISTS(SELECT 1 FROM EXT.MODIFICAR_MEDIADOR MM WHERE MM.COD_MEDIADOR =  LPAD(M.IDMEDIADOR,4,0) AND MM.SUBCLAVE = LPAD(M.IDSUBCLAVE,4,0))
						THEN 'NO EXISTE MEDIADOR'
					WHEN NOT EXISTS(SELECT 1 FROM EXT.MODIFICAR_MEDIADOR MM WHERE MM.COD_MEDIADOR =  LPAD(M.IDMEDIADOR,4,0) AND MM.SUBCLAVE = LPAD(M.IDSUBCLAVE,4,0)
							AND COALESCE(TERMINATIONDATE,'2200-01-01') = '2200-01-01')
						THEN 'MEDIADOR DADO DE BAJA'
					WHEN NOT EXISTS(SELECT 1 FROM EXT.CARTERA WHERE RAMO = 'CREDITO' AND NUM_POLIZA = M.NUM_POLIZA AND ACTIVO > 0) 
						THEN 'PÓLIZA NO REGISTRADA EN CARTERA'
					WHEN NOT EXISTS(SELECT 1 FROM EXT.CARTERA WHERE RAMO = 'CREDITO' AND NUM_POLIZA = M.NUM_POLIZA AND NUM_ANUALIDAD = M.NUM_ANUALIDAD AND ACTIVO > 0) 
						THEN 'ANUALIDAD NO REGISTRADA EN CARTERA'
					WHEN NOT EXISTS(SELECT 1 FROM EXT.CARTERA WHERE RAMO = 'CREDITO' AND NUM_POLIZA = M.NUM_POLIZA AND NUM_ANUALIDAD = M.NUM_ANUALIDAD
					AND LPAD(M.IDMEDIADOR,4,0) ||'-'|| LPAD(M.IDSUBCLAVE,4,0) = LPAD(COD_MEDIADOR,4,0) ||'-'|| LPAD(COD_SUBCLAVE,4,0) AND ACTIVO > 0) 
						THEN 'MEDIADOR DISTINTO EN CARTERA'
					WHEN NOT EXISTS(SELECT 1 FROM EXT.CARTERA WHERE RAMO = 'CREDITO' AND NUM_POLIZA = M.NUM_POLIZA AND NUM_ANUALIDAD = M.NUM_ANUALIDAD
					AND LPAD(M.IDMEDIADOR,4,0) ||'-'|| LPAD(M.IDSUBCLAVE,4,0) = LPAD(COD_MEDIADOR,4,0) ||'-'|| LPAD(COD_SUBCLAVE,4,0) AND M.FECHA_EFECTO = FECHA_EFECTO AND ACTIVO > 0) 
						THEN 'FECHA EFECTO DISTINTA EN CARTERA'
					WHEN NOT EXISTS(SELECT 1 FROM EXT.CARTERA WHERE RAMO = 'CREDITO' AND NUM_POLIZA = M.NUM_POLIZA AND NUM_ANUALIDAD = M.NUM_ANUALIDAD
					AND LPAD(M.IDMEDIADOR,4,0) ||'-'|| LPAD(M.IDSUBCLAVE,4,0) = LPAD(COD_MEDIADOR,4,0) ||'-'|| LPAD(COD_SUBCLAVE,4,0) AND M.FECHA_EFECTO = FECHA_EFECTO AND M.FECHA_VENCIMIENTO = FECHA_VENCIMIENTO AND ACTIVO > 0) 
						THEN 'FECHA VENCIMIENTO DISTINTA EN CARTERA'
					ELSE 'OK. EXISTE EN CARTERA'
				END AS MOTIVO
				, M.IDMODALIDAD
				, M.NUM_POLIZA
				, M.NUM_ANUALIDAD AS ANUALIDAD
				, LPAD(M.IDMEDIADOR,4,0) || '-' || LPAD(M.IDSUBCLAVE,4,0) IDMEDIADOR
				, M.FECHA_EFECTO
				, M.FECHA_VENCIMIENTO
				, M.FECHA_INI AS FECHA_INICIO
				, M.FECHA_FIN AS FECHA_FIN
				, M.BATCHNAME
			FROM EXT.EXT_MOVIMIENTO_CARTERA_CREDITO_HIST M
			WHERE M.BATCHNAME LIKE CASE WHEN i_FILENAME IS NULL OR i_FILENAME = '' THEN '%MVCAR%' ELSE '%'||i_FILENAME||'%' END
			AND NOT EXISTS(SELECT 1 FROM EXT.CARTERA WHERE RAMO = 'CREDITO' AND NUM_POLIZA = M.NUM_POLIZA AND NUM_ANUALIDAD = M.NUM_ANUALIDAD
						AND LPAD(M.IDMEDIADOR,4,0) ||'-'|| LPAD(M.IDSUBCLAVE,4,0) = LPAD(COD_MEDIADOR,4,0) ||'-'|| LPAD(COD_SUBCLAVE,4,0) AND M.FECHA_EFECTO = FECHA_EFECTO AND M.FECHA_VENCIMIENTO = FECHA_VENCIMIENTO
						AND ACTIVO > 0
			)
			-- v02: filtramos período de intermediación fuera de la fecha de vigencia 
			AND 1 = ( CASE WHEN EXISTS(SELECT 1 FROM EXT.CARTERA WHERE RAMO = 'CREDITO' AND ACTIVO > 0 AND NUM_POLIZA = M.NUM_POLIZA AND NUM_ANUALIDAD = M.NUM_ANUALIDAD 
            							AND LPAD(M.IDMEDIADOR,4,0) ||'-'|| LPAD(M.IDSUBCLAVE,4,0) <> LPAD(COD_MEDIADOR,4,0) ||'-'|| LPAD(COD_SUBCLAVE,4,0) AND M.FECHA_EFECTO NOT BETWEEN M.FECHA_INI AND M.FECHA_FIN 	AND M.FECHA_VENCIMIENTO NOT BETWEEN M.FECHA_INI AND M.FECHA_FIN )
							THEN 0 
            				ELSE 1 END )
			-- fin v02
			ORDER BY NUM_POLIZA
			;
		
	END